services:
  db:
    container_name: "mysql_database_flask"
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin123"
      MYSQL_ROOT_PASSWORD: "admin123"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql_database_flask:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d


volumes:
  mysql_database_flask:
    name: mysql_database_flask